const puppeteer = require('puppeteer-core');

(async () => {
    const url = 'http://localhost:3000/';
    const browser = await puppeteer.launch({
        executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
        headless: false,
        defaultViewport: null,
    });

    let pages = [];

    // Chrome launches with a default page, set that as page one.
    let defaultPages = await browser.pages();
    pages.push(defaultPages[0]);

    // Set up for host
    let host = pages[0];
    await host.goto(url);
    await enterNickname(host, 'Test');
    await clickCreateLobby(host);

    // Wait until room code appears
    await host.waitForSelector('h3#room-code', {
        visible: true,
    });

    // Get roomCode generated by the backend
    let roomCode = await host.evaluate(() => {
        roomCode = document.querySelector('h3#room-code').innerText;
        return roomCode.substr(roomCode.lastIndexOf(' ') + 1);
    });

    for (let i = 1; i < 6; i++) {
        pages.push(await browser.newPage());
        await pages[i].goto(url);
        await enterNickname(pages[i], (i + 1).toString());
        await enterRoomCode(pages[i], roomCode);
        await clickJoin(pages[i]);
    }

    // Bring the browser focus back to the host page and click the start game button
    await host.bringToFront();
    busyWait(2);
    await host.evaluate(() => {
        document.querySelector('button#start-game').click();
    });
})();

async function enterNickname(page, nickname) {
    await page.type('input#nickname', nickname);
}

async function enterRoomCode(page, roomCode) {
    await page.type('input#room-code', roomCode);
}

async function clickJoin(page) {
    await page.evaluate(() => {
        document.querySelector('button#join-lobby').click();
    });
}

async function clickCreateLobby(page) {
    await page.evaluate(() => {
        document.querySelector('button#create-lobby').click();
    });
}

function busyWait(seconds) {
    var until = new Date(new Date().getTime() + seconds * 1000);
    while (until > new Date()) {}
}
