name: Backend Tests
on: pull_request
jobs:
  backendTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      working-directory: ./backend
      run: npm ci
    - name: Run backend tests
      working-directory: ./backend
      run: npm run test
